### ISSUE TITLE
Why is this GPL?

### ISSUE THREAD

**Issue by 8bitprodigy** [winft/como#18]
I mean,  if it's a library, shouldn't it be something a bit more permissive, like at least LGPL? I think GPL would drive people away from using this.

**Comment by romangg** [comment]
I think for a compositor it's not that vital to have a permissive license. Because you can usually insert it even into some proprietary tech stack without problems as the interaction happens through protocols and other APIs.

**Comment by 8bitprodigy** [comment]
That... misses the point entirely.
My point is, one may want to be able to decide what license they put their program under, and by licensing this library as GPL instead of something like MIT or even LGPL, they cannot give their compositor such a license. The people over at RavynOS already turned this up for Louvre due to that being MIT.

**Comment by romangg** [comment]
Ok, I didn't know what your motivation is behind the question.

The reasons for gpl are:
* Code is in parts from KWin, which is gpl. So it must stay gpl.
* For me personally: I believe gpl is better suited for a compositor library and compositor project. It doesn't hinder adoption in commercial reasons for reasons giving above and on the other side permissive licenses make it too easy in general to use code without giving back.

I hope that sufficiently explains why it is gpl. Thanks for asking.

**Comment by 8bitprodigy** [comment]
Really? I literally just explained it.
Okay, I can understand the KWin part, but as for the other point, just because *you* don't have an issue with it, that doesn't mean *others* won't, regardless of whether it can be used in a commercial setting or not. At the end of the day, some people might want control over how they can license code that they write, and a library in GPL would be a hindrance to that. Get the picture?
